name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git identity
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: Pull from Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull https://VA6573:$HF_TOKEN@huggingface.co/spaces/VA6573/Search_Engine_LLAMA3-8b-8192 main --allow-unrelated-histories || true

      - name: ✅ Force push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://VA6573:$HF_TOKEN@huggingface.co/spaces/VA6573/Search_Engine_LLAMA3-8b-8192 main
